apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: myapp1-deployment
  namespace: qa
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:  
    metadata: # Dictionary
      name: myapp1-pod
      labels: # Dictionary
        app: myapp1  # Key value pairs
    spec:
      containers: # List
        - name: myapp1-container
          image: stacksimplify/kubenginx:1.0.0
          ports: 
            - containerPort: 80  
          resources:
            requests:
              memory: "128Mi" # 128 MebiByte is equal to 135 Megabyte (MB)
              cpu: "450m" # `m` means milliCPU
            limits:
              memory: "256Mi"
              #cpu: "600m"  # This is above the max value defined in Limit Range, Pods will not be scheduled and error thrown when we refer ReplicaSet Events
              cpu: "500m" # This is equal to Max value defined in LimitRange, Pods will be scheduled.   