apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-incoming-8080-1-2
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: test1
    ports:
      - protocol: TCP
        port: 8080
        endPort: 8082