apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-webapp  
  labels:
    app: usermgmt-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-webapp
  template:  
    metadata:
      labels: 
        app: usermgmt-webapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: usermgmt-webapp
          image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
          ports: 
            - containerPort: 8080           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webappdb"            
            - name: DB_USERNAME
              value: "root"            
            #- name: DB_PASSWORD
            #  value: "dbpassword11"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password 
          # Liveness Probe HTTP Request
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
              httpHeaders:
              - name: Custom-Header
                value: Awesome          
            initialDelaySeconds: 60 # initialDelaySeconds field tells  the kubelet that it should wait 60 seconds before performing the first probe. 
            periodSeconds: 10 # periodSeconds field specifies kubelet should perform a liveness probe every 10 seconds. 
            failureThreshold: 3 # Default Value
            successThreshold: 1 # Default value


# Types of Liveness Probes we can define
# 1. Linux Command
# 2. HTTP Request
# 3. TCP Ping                                        

# What happens ??
# 1. To perform a probe, the kubelet sends an HTTP GET request to the 
# server that is running in the container and listening on port 8080. 
# 2. If the handler for the server's /login path returns a success code,
# the kubelet considers the container to be alive and healthy. 
# 3. If the handler returns a failure code, the kubelet kills the 
# container and restarts it.                                  
# 4. Any code greater than or equal to 200 and less than 400 
# indicates success. Any other code indicates failure.