apiVersion: v1
kind: Service
metadata:
  name: cdn-demo-nodeport-service
  annotations:
    cloud.google.com/backend-config: '{"default": "my-backendconfig"}'     
spec:
  type: NodePort
  selector:
    app: cdn-demo
  ports:
    - port: 80
      targetPort: 8080